version: '3.7'
services:
  discordshim:
    image: discordshim
    build: .
    ports:
      - "${EXTERNAL_PORT}:23416"
    environment:
      - DISCORD_TOKEN=${BOT_TOKEN}
      - RUST_LOG=debug,tracing::span=off
      - RUST_BACKTRACE=full
    restart: always